project:
  type: website
  output-dir: docs

website:
  title: "Ana Bravo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - Teaching (coming soon)
    tools:
      - icon: github
        text: GitHub
        href: https://github.com/anbrav0
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/anabravobiostats/
      - icon: mastodon
        text: Mastodon
        href: https://fosstodon.org/@anabananapie
  
format:
  html:
    theme: 
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]

editor: visual

