project:
  type: website

website:
  title: "Ana Bravo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
  
format:
  html:
    theme: 
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]

editor: visual

